spring.application.name=sharemap

# =========================
# PostgreSQL (Railway)
# =========================
spring.datasource.url=jdbc:postgresql://kodama.proxy.rlwy.net:19229/railway
spring.datasource.username=postgres
spring.datasource.password=HnLdzvVgfQvzsyubqcygsDGqafsjdxwn
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Thymeleaf
# =========================
spring.thymeleaf.cache=false

# =========================
# Kakao API
# =========================
kakao.api.key=66d015a0ab83c400b1697ae94916643a

server.port=${PORT:8080}