spring.application.name=sharemap

# =========================
# PostgreSQL (Railway)
# =========================
spring.datasource.url=jdbc:postgresql://zephyr.proxy.rlwy.net:32188/railway
spring.datasource.username=postgres
spring.datasource.password=FYOgWPcbMSbsgZXtLLukmdoIwGaOuwsB
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# =========================
# Thymeleaf
# =========================
spring.thymeleaf.cache=false

# =========================
# Kakao API
# =========================
kakao.api.key=66d015a0ab83c400b1697ae94916643a

# =========================
# Server
# =========================
server.port=${PORT:8080}